In [4]:
import tensorflow as tf
#!pip install opencv
# import opencv
import os
import pandas as pd
import numpy as np
print(tf.__version__, pd.__version__, np.__version__)

2.13.0 1.2.5 1.24.3


In [78]:
###################### CREATING alL kinds of Matrix in Tensorff\low @@@@@@@@@@@@@@@

v1 = v = tf.Variable([4], dtype='float32')
mat0=tf.constant([[5]]) ######## 1 by 1 Matrix

mat1=tf.constant([[1,2,3], [4,5,6], [8,10,7]] ,dtype='float32')  ####### 2 by 2 Matrix 

mat2=tf.zeros((3,3))   ########## Three by Three Zeros Matrix


mat4=tf.ones((3,3))  ###############  ONEs ALL OVER Square Matrix @@@@@@@@@@@@@@@@@@@@@

mat3=tf.eye(3)       ############## 3 by 3 IDNETITY MATRIX HAVE ONES ACROSS DIAGONAL and Zeros ELSE Where @@@@@@@@@@@@

mat6=tf.eye(3)*4  ######## SCALR Square Matrix idenity matrix multiplied by Scalar Lambda =4 @@@@@@@ 

print (mat6,v1, mat0, mat1, mat4, mat1, mat2, mat3)  ############ PRINT all MATRICES ABOVE @@@@@@@@@@@@@@@

############## HOW to COMPUTE RANK of a MATRIX USING Tensorflow @@@@@@@@@@@@@@@@@@

tf.linalg.matrix_rank(mat6)

############## COMPUTE the DETERMINAVT of a MATRIX Using Tensorflow @@@@@@@@@@@@@@@
#tf.linalg.det(mat1)

tf.Tensor(
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]], shape=(3, 3), dtype=float32) <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)> tf.Tensor([[5]], shape=(1, 1), dtype=int32) tf.Tensor(
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 8. 10.  7.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 8. 10.  7.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [79]:
mat4= tf.constant([[2,4,5], [10,5,8],[8,9,20]],dtype='float32') ### Matrix of rAnk n=3
ma5= tf.zeros((5,5)) ########### zero matrix of rank =5
ma6= tf.eye(5,5)  ############## Idenitty matrix 

ma7= tf.constant([[5]])  ############## Idenitty matrix 

print(ma7)


print(mat4)
print(ma5)
print(ma6)

tf.Tensor([[5]], shape=(1, 1), dtype=int32)
tf.Tensor(
[[ 2.  4.  5.]
 [10.  5.  8.]
 [ 8.  9. 20.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [87]:
rank1=tf.linalg.matrix_rank(mat6)
#tf.matrix_determinant(mat1)
det1=tf.linalg.det(mat1)
#nmat8= np.eye(mat1)
print(det1, rank1)
#tf.linalg.det(input=nmat8,name=None)

#tf.linalg.det(mat1)

mat9 = tf.transpose(mat1)
print(mat9)

mat10 = tf.linalg.inv(mat1)
print(mat10)

tf.Tensor(15.000001, shape=(), dtype=float32) tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[ 1.  4.  8.]
 [ 2.  5. 10.]
 [ 3.  6.  7.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-1.6666667   1.0666667  -0.20000006]
 [ 1.3333334  -1.1333334   0.40000004]
 [ 0.          0.4        -0.2       ]], shape=(3, 3), dtype=float32)
